# Generated by Django 3.2.2 on 2021-07-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_patient_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='timestamp',
            field=models.TimeField(),
        ),
    ]
