# Generated by Django 3.2.2 on 2021-07-02 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20210702_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test', models.CharField(max_length=64)),
                ('Name', models.CharField(max_length=64)),
                ('Date', models.DateField()),
                ('Active', models.BooleanField(default=True)),
                ('timestamp', models.TimeField()),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Patient', models.ManyToManyField(blank=True, related_name='patients_name_test', to='appointments.patient')),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.location')),
            ],
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=64)),
                ('Name', models.CharField(max_length=64)),
                ('Date', models.DateField()),
                ('Active', models.BooleanField(default=True)),
                ('timestamp', models.TimeField()),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Patient', models.ManyToManyField(blank=True, related_name='patients_name_med', to='appointments.patient')),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.location')),
            ],
        ),
    ]
