# Generated by Django 3.2.2 on 2021-07-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_medicine_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='timestamp',
        ),
    ]
